source 'git@bitbucket.org:codedazur/cda-ios-pods.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CDASyncCoreDataParser_Example', :exclusive => true do
  pod 'CDASyncCoreDataParser', :path => '../'
end

target 'CDASyncCoreDataParser_Tests', :exclusive => true do
  pod 'CDASyncCoreDataParser', :path => '../'

  pod 'Kiwi'
end
